/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.asteriskjava.fastagi.*;

public class HelloAgiScript extends BaseAgiScript{
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new HelloAgiScript().getGreeting());
    }

    @Override
    public void service(AgiRequest request, AgiChannel channel) throws AgiException {

        answer();

        streamFile("welcome");
        streamFile("tt-monkeys");

        hangup();
    }
}
